overleaf/filestore

.travis.yml
Gruntfile.coffee
app/coffee/FSPersistorManager.coffee
app/coffee/FileHandler.coffee
package.json
test/acceptence/coffee/SendingFileTest.coffee
test/unit/coffee/FSPersistorManagerTests.coffee
test/unit/coffee/FileHandlerTests.coffee

Code changes:  FileHandler deleteFile method
-  fix use of converted bucket name (only first argument of getConvertedFolderKey is used)
- call deleteDirectory on converted cache directory, to make deleteFile inverse of insertFile
FS-only changes:
- use rimraf to delete directory recursively
- use 'response' module to return HTTP "NoSuchKey" response for missing file, as on S3
- copyFile calls success callback on completion, instead of immediately
Test changes:
- updates to match above
- run acceptance tests with forever on travis

Fix acceptance tests for filestore, run on travis

---

app/coffee/FileConverter.coffee
app/coffee/SafeExec.coffee
test/unit/coffee/FileConverterTests.coffee
test/unit/coffee/SafeExec.coffee

Create a new SafeExec module to run file conversion processes in detached mode, with a new process group, so they can be terminated reliably.

Use process group to terminate processes

---

app.coffee
app/coffee/BucketController.coffee
app/coffee/FileHandler.coffee
app/coffee/S3PersistorManager.coffee
config/settings.defaults.coffee
test/unit/coffee/BucketControllerTests.coffee
test/unit/coffee/S3PersistorManagerTests.coffee
test/unit/coffee/SettingsTests.coffee

Add `/bucket/:bucket/key/*`, which fetches the file from the given bucket at the given path. Uses auth stored at `settings.filestore.s3.{{bucketName}}` if present, and otherwise default auth.
This is to support the use case where:
- v1 makes a CLSI request to v2, 
and
- request contains file URLs stored on S3, 
and
- they are not in the default bucket that v2 would use for its own files, 
and
- CLSI is in a contained environment and cannot reach S3 except through filestore.
Child of https://github.com/overleaf/sharelatex/issues/664
Child of https://github.com/overleaf/sharelatex/issues/507

Add endpoint for arbitrary bucket fetch

---

Dockerfile

In the dev environment the image conversions currently don't work due to missing packages for `ghostscript` and `optipng`.  This adds a project-specific docker file to install them.

add dockerfile to install packages needed by filestore

---

app/coffee/FileHandler.coffee
app/coffee/LocalFileWriter.coffee
test/unit/coffee/FileHandlerTests.coffee
test/unit/coffee/LocalFileWriterTests.coffee

When we write a converted file to S3 we immediately try to read it back, but this violates the conditions for read-after-write consistency because we earlier check if the file exists (https://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel).
In this case we want to serve the original file back to the user from disk, and serve the file contents on disk for subsequent requests.
(To work properly in all cases I had to make the backends consistent in https://github.com/sharelatex/filestore-sharelatex/pull/34)

serve file from disk to avoid read-after-write inconsistency

---

app/coffee/FSPersistorManager.coffee
app/coffee/S3PersistorManager.coffee
test/unit/coffee/FSPersistorManagerTests.coffee

Currently the different filestore backends `FSPersistor`, `AWSSDKPersistor` and `S3Persistor` have different behaviours for `sendFile` and `sendStream`, with regard to deleting the uploaded file and/or temporary files that they create.
This PR makes them consistent as follows:
- `sendFile` (which  uploads a supplied file to S3) should not delete the original file, leaving that the the caller.
- `sendStream` (which uploads a stream to S3, which is done by storing it as a file and then calling `sendFile`) should delete the temporary file it creates.
The previous logic was
| Module | `sendFile` | `sendStream` |
| ------------ | -- | ---| 
| FSPersistor |   deletes input file | leaves temporary file in upload directory |
| S3Persistor | deletes input file |  deletes temporary file by calling …

make filestore backends consistent

---

app/coffee/FileController.coffee
app/coffee/FileHandler.coffee
app/coffee/S3PersistorManager.coffee

We are logging huge numbers of `Not Found` errors from loading templates which either don't have thumbnails (the creation of the thumbnail failed for some reason) or the template pdf wasn't uploaded. We can at least suppress these from sentry by not logging them as errors.

reduce logging of not found errors

---

npm-shrinkwrap.json
package.json

to avoid double-logging and filter paths from sentry errors

upgrade logger-sharelatex to v1.5.8

---

Dockerfile

The update and install lines need to be run together, because `RUN apt-get update` is cached in other builds and may be out of date.

avoid problems with caching of apt-get operations

---

app/coffee/S3PersistorManager.coffee
test/unit/coffee/S3PersistorManagerTests.coffee

to work around problems with knox error handling making the S3 copy operation unreliable.
I have tested this locally using the staging s3 credentials.  Only replacing the copy operation at this stage, as it is the only one which we have encountered actual problems with.  The other operations can be migrated to the AWS SDK later.
connects to https://github.com/overleaf/sharelatex/issues/1225

use the aws sdk to copy files in S3PersistorManager

---

app/coffee/ImageOptimiser.coffee
app/coffee/SafeExec.coffee
config/settings.defaults.coffee
test/unit/coffee/ImageOptimiserTests.coffee
test/unit/coffee/SafeExecTests.coffee

We can't really trust the convert commands in filestore on k8 due to lack of firejail sandboxing, this flag hard disables there functionality until we have a better system available. I've not checked on user facing impact of previewing `eps` and `pdf` image in the editor yet, this PR is just for security reasons.
Child of https://github.com/overleaf/sharelatex/issues/552

Disable exec with settings flag

---

app/coffee/FileController.coffee
app/coffee/S3PersistorManager.coffee
test/unit/coffee/FileControllerTests.coffee
test/unit/coffee/S3PersistorManagerTests.coffee

This returns a 404 error (instead of a 500) when copying a missing file.  We have many projects lurking with missing files and we need a way to detect this in web if we want to handle it gracefully.
connects to https://github.com/overleaf/sharelatex/issues/1225

return a 404 error (instead of a 500) when copying a missing file

---

app.coffee

Noticed this error in the google logs, the `close` method is actually on the `server` object.
```
filestore_1               | /app/app.js:167
filestore_1               |       app.close(function() {
filestore_1               |           ^
filestore_1               | 
filestore_1               | TypeError: app.close is not a function
filestore_1               |     at beginShutdown (/app/app.js:167:11)
filestore_1               |     at process.<anonymous> (/app/app.js:192:12)
filestore_1               |     at emitNone (events.js:86:13)
filestore_1               |     at process.emit (events.js:185:7)
filestore_1               |     at Signal.wrap.onsignal (internal/process.js:199:44)
```
NA
NA
2 line change
Low
NA
NA
NA
NA
@henryoswald @mans0954

fix beginShutdown to use server.close()

---

app.coffee
app/coffee/FSPersistorManager.coffee
app/coffee/FileController.coffee
app/coffee/FileHandler.coffee
app/coffee/S3PersistorManager.coffee
test/acceptance/coffee/SendingFileTest.coffee
test/unit/coffee/FSPersistorManagerTests.coffee
test/unit/coffee/FileControllerTests.coffee
test/unit/coffee/FileHandlerTests.coffee
test/unit/coffee/S3PersistorManagerTests.coffee

This will be used by the file preview feature when it gets partial content.
* overleaf/issues#1885
I deliberately used the AWS SDK directly instead of the [knox library](https://github.com/Automattic/knox). This library looks unmaintained (54 open issues, last issue closed in 2015, last commit in 2016).
Anything that makes HEAD requests on the filestore service will see an additional Content-Length header and might get confused. This is very unlikely, though.
Filestore serves 3 kinds of files: user files, templates and public files. User files can be tested by uploading a file to a project. I'm not sure how to test the two other kinds.

Return file size on HEAD request

---

app/coffee/S3PersistorManager.coffee
test/unit/coffee/S3PersistorManagerTests.coffee

The AWS SDK has a retry strategy to deal with rate limiting or transient
unavailability of S3. We hope it will reduce our error rates.
* https://github.com/overleaf/issues/issues/1793
This piece of code is called from the following endpoints:
* GET /project/:project_id/file/:file_id
* GET /template/:template_id/v/:version/:format
* GET /project/:project_id/public/:public_file_id
* GET /bucket/:bucket/:key/*
See if that stops us from failing on 503s from S3 (https://sentry.io/organizations/overleaf/issues/682378420/?project=60782)

Use AWS SDK for getFileStream()

---

app/coffee/S3PersistorManager.coffee
test/unit/coffee/S3PersistorManagerTests.coffee

In 49a21155f642670dfea264ac73fb60241f37cb87, I managed to incorrectly
write the `createUnbufferedStream()` function from the AWS SDK as
`getUnbufferedStream()` and to consistently use that naming in the unit
tests.
This commit fixes that. I have tested again on S3.
Cause: https://github.com/overleaf/filestore/pull/53

Fix createUnbufferedStream() function call

---

.github/PULL_REQUEST_TEMPLATE.md
Makefile
buildscript.txt
docker-compose.ci.yml
docker-compose.yml

Clarifies that this is an open source repo and updates the PR template link for contributing.
@mans0954 I did have to manually touch some of the files because https://github.com/overleaf/filestore/blob/43b8a9093b8d1d394bbd6111ac19221faef5e05c/docker-compose.yml#L31 and https://github.com/overleaf/filestore/blob/43b8a9093b8d1d394bbd6111ac19221faef5e05c/docker-compose.ci.yml#L25 have been added manually. Should we add them via the buildscript? I'm just not sure how to add a key value pair via `env-pass-through`.
https://github.com/overleaf/issues/issues/2403

Update PR template to reflect current open source docs

---

app/coffee/S3PersistorManager.coffee
config/settings.defaults.coffee
docker-compose.ci.yml
docker-compose.yml
test/acceptance/coffee/FilestoreApp.coffee
test/acceptance/coffee/SendingFileTest.coffee
test/unit/coffee/S3PersistorManagerTests.coffee

Primarily, this adds `s3.ingress` and `s3.egress` metrics to Filestore.
In order to test this, I wanted to write an acceptance test that verifies the metric. This involved:
* Adding a fake S3 container to the docker test environment
* Configuring the test environment to use S3 instead of the filesystem
* Setting `USE_PROM_METRICS` so that we can scrape the `/metrics` endpoint
Removed the unused `AWSSDKPersistorManager`. It's confusing having two AWS persistors.
Renamed a local `request` variable to `s3request`. The former was overwriting the global `request` object in a way that broke other methods in the file. This only became apparent when S3 was being used for the accpetance tests. Specifically, the methods were `deleteFile` and `checkIfFileExists`. I don't think we have anything …

Add metrics for S3 ingress and egress, and improve acceptance tests

---

app/coffee/FSPersistorManager.coffee
test/unit/coffee/FSPersistorManagerTests.coffee

This PR adds support for node version 10 and above.
Attaching a `readable` listener to a `Readable` stream causes the stream to hang on node version 10 [1].
REF https://github.com/sharelatex/filestore-sharelatex/pull/40
---
[1] See last sentence in this paragraph: https://nodejs.org/api/stream.html#stream_two_reading_modes

[misc] add support for node 10+

---

app/js/Errors.js
app/js/FileHandler.js
app/js/LocalFileWriter.js
npm-shrinkwrap.json
package.json
test/unit/js/FileHandlerTests.js
test/unit/js/LocalFileWriterTests.js

One in a series of decaf-cleanup PRs. This cleans up and adds promise support for `FileHandler` and `LocalFileWriter`.
Original decaf work was in #60 
~Based onto #63~
Based onto #62
Trying to keep these as small as possible, but this one is a bit unwieldy, sorry.

Decaf cleanup for FileHandler and LocalFileWriter

---

app/js/FileConverter.js
test/unit/js/FileConverterTests.js

Part of a series of decaf-cleanup PRs, starting at #60 
This one is targeted onto #64 
This cleans up and promisifies `FileConverter`. As well as promisification, I've also removed some duplicate code present in all of the different conversion methods.

Cleanup and promisify FileConverter

---

app.js
app/js/Errors.js
app/js/HealthCheckController.js
app/js/KeyBuilder.js

Follows on from #60 which is the initial decaf PR
Targeted onto #65 
Cleans up the health-check controller, to call into the APIs directly instead of faking a call to a controller. It's a lot cleaner this way.
Also renamed `KeyBuilder.userFileKey` and friends, to e.g. `KeyBuilder.userFileKeyMiddleware` so that it's obvious what they are.

Clean up and promisify health-check controller and KeyBuilder

---

app/js/ImageOptimiser.js
test/unit/js/ImageOptimiserTests.js

Further cleanup of the decaf started in #60 
This PR cleans up `ImageOptimiser`, and is targeted onto #66 - there are many PRs in this chain as I am trying to spread out the review workload.
Removed the calls directly into `child_process` and instead call directly into `SafeExec`. This also checks that image optimisation is enabled, so removed the redundant check from here.

Decaf and promisify ImageOptimiser

---

app/js/FSPersistorManager.js
app/js/LocalFileWriter.js
npm-shrinkwrap.json
package.json
test/acceptance/js/FilestoreTests.js
test/unit/js/FSPersistorManagerTests.js
test/unit/js/LocalFileWriterTests.js

Yet more decaf cleanup. Started in #60 and targeted onto #68. This cleans up `FSPersistorManager`.
The changes are quite significant so are a bit awkward to read. Sorry about that. Trying to spread these around between reviewers.
Due to the changes in #68, the acceptance tests run for both these and S3, which is helpful to make sure nothing has broken.
I removed the call to `fs.exists` which is deprecated, and replaced with `fs.stat`. I've also moved from using `pipe` to `pipeline`.

Decaf cleanup and promisification for FSPersistorManager

---

app/js/FileController.js
app/js/HealthCheckController.js
test/unit/js/FileControllerTests.js

This cleans up FileController. I didn't promisify this one as it deals with expressjs controller methods which are already callbacky, and it's not doing anything too complex anyway.
Removed deprecated `res.send` from `HealthcheckController` as well as `FileController`.
As usual, I'm trying to spread these reviews around a bit.
Part of the work started in #60 and targeted onto #69 
I jiggled the tests around slightly so that it's not testing an internal method. (`_getRange`) - This is now not exposed as part of the module. Interestingly, this exposed a bug in the original implementation where it will crash if you pass an invalid `range` header due to the lack of a null check from `_getRange`. I've fixed this.

Decaf cleanup of FileController

---

app/js/PersistorManager.js
test/unit/js/KeybuilderTests.js
test/unit/js/PersistorManagerTests.js

Part of the ongoing decaf-cleanup work. This cleans up three fairly simple files. There was no need for any promisification in these.
`PersistorManager` is responsible for including the right file based on settings. There is one functional change here, in that it now throws an error if the backend is not configured, instead of trying to load s3. I rewrote the `PersistorManagerTests` as these seemed quite old, and weren't really testing sensible things. The tests now ensure that the correct file is included for the relevant settings.
`KeyBuilderTests` required only slight modification. `KeyBuilder` was already cleaned up, but I forgot the tests last time.
Spreading these PRs around, as there are a lot of them.
Decaf work started in #60 
This PR is targeted onto the branch for #70

Post-decaf cleanup of PersistorManager and KeyBuilderTests

---

app/js/FileController.js
app/js/S3PersistorManager.js
test/unit/js/S3PersistorManagerTests.js

This will report `AccessDenied` from S3 as a 404, and not generate any log info when we get a `ERR_STREAM_PREMATURE_CLOSE` back from `pipeline`.
The former was happening anyway on the old version and generating errors in Stackdriver, but the errors look different now so generated a new alert in Sentry.

Handle AccessDenied and stream-premature-close errors

---

app.js
app/js/Errors.js
app/js/FSPersistorManager.js
app/js/FileController.js
app/js/FileConverter.js
app/js/FileHandler.js
app/js/HealthCheckController.js
app/js/ImageOptimiser.js
app/js/LocalFileWriter.js
app/js/RequestLogger.js
app/js/S3PersistorManager.js
app/js/SafeExec.js
test/unit/js/FSPersistorManagerTests.js
test/unit/js/FileControllerTests.js
test/unit/js/FileConverterTests.js
test/unit/js/FileHandlerTests.js
test/unit/js/ImageOptimiserTests.js
test/unit/js/KeybuilderTests.js
test/unit/js/LocalFileWriterTests.js
test/unit/js/S3PersistorManagerTests.js
test/unit/js/SafeExecTests.js

**Re-opening of #75**
Accidentally closed that PR by cleaning up some stale branches, and now I can't reopen it again.
An attempt to reduce log volume to (mostly) one log per request, as described in the logging proposal. Specifically, this does the following:
* Removes access to the logger from (almost) everywhere
* Adds a logging middleware to express, and a logging error handler
* Call either `next()` or `next(err)` from all non-health-check controller methods
This results in one happy-path log per request, *or* one error log.
Previously opened as #75
The logging proposal is in overleaf/write_latex_ops#531
In addition to the comments made in the previous PR, I took the logic from `metrics-sharelatex`'s HTTP monitor, which records timing info for the http methods as well as acting as a …

Simplify logging to only log once per request

---

.dockerignore
install_deps.sh

I happen to have to rebuild the docker image again and it took ages. A quick inspection showed that you are still building an ancient version of ghostscript from source. We are using the debian package for imagemagick, so it should be fine to use their ghostscript package too. It is likely that they retain compatibility between the two, would on jump out of the line.
Program failures during the install_deps stage are no longer discarded, which reviled that the data dirs are included into the docker image - this was likely the trigger for the rebuild mentioned earlier. The data dirs are excluded from the COPY stage.
Low, ghostscript is used for pdf to image conversion, which we do not allow in production.
- _[There is an acceptance test for the …

[misc] cleanup install deps

---

app/js/FSPersistor.js
app/js/PersistorHelper.js
app/js/S3Persistor.js
test/unit/js/FSPersistorTests.js
test/unit/js/S3PersistorTests.js

This adds a `PersistorHelper` (bit of a mouthful but I couldn't think of a better name for it) which contains some common functionality for the current persistors, and the new GCS persistor when it is ready.
Currently based onto `spd-migration-persistor` until that is merged.
Part of the work for overleaf/google-ops#731
Currently only `_wrapError` is shared by `FSPersistor` and `S3Perisstor`, but the other functionality here is useful to `GCSPersistor` as well.
I think it also makes a couple of mechanisms clearer - for example, the `waitForStreamReady` mechanism was bundled up as part of the general download logic and putting it in its own method defines what it's trying to do a bit more obviously.
There aren't any unit tests for `PersistorHelper`. Instead, I opted to test the …

Refactor persistors to use a helper for common things

---

app/js/RequestLogger.js

The line in the error handler to assign the error variable to the request handler was incorrect.
The handler is static, and so `this._logInfo` does not make any sense here. We should use the `requestLogger` object on the request instead.

Fix log info assignment in error handler

---

app.js
app/js/RequestLogger.js

I missed the part where it says "You define error-handling middleware last, after other app.use() and routes calls" in https://expressjs.com/en/guide/error-handling.html - so the error handler isn't firing. This means that the logged errors to not include the `error` object.
This moves things around to fix that.
Only affects the way that errors are reported

Move error handler to be the last middleware

---

app/js/S3Persistor.js
config/settings.defaults.coffee
test/acceptance/js/FilestoreTests.js
test/unit/js/S3PersistorTests.js

When uploading a file, we verify the md5 based on the eTag. By default, `upload` will use a multipart upload if the file is over 5MiB.
When using a multipart upload, the md5 hash is not correctly calcuated, and is returned in a different format.
This PR:
- sets the max chunk size to 100MiB, to ensure files are uploaded in a single part
- fetches the file to calculate the md5 in the case where the md5 is not in the correct format
The latter should fix issues where we need to calculate the md5 hash of a file stored in S3 which has been uploaded as a multipart upload. This shouldn't need to happen very often.
Without setting the chunk size, this could cause a lot of additional ingress as we would be re-downloading any >5MiB file. However, in pretty much every case we should be uploading in a …

Fix eTags not being in md5 format for large files

---

.eslintrc
.prettierrc
Dockerfile
Makefile
buildscript.txt
docker-compose.ci.yml
docker-compose.yml
package.json

The latest version of Prettier wants to be run with a full path instead of a relative one. This change calls Prettier with `$PWD` prepended to the path.
Introduced in #99 
Fix from https://stackoverflow.com/questions/60103564/there-was-trouble-creating-the-eslint-cliengine

Fix prettier task

---

config/settings.defaults.coffee

Simple default from an environment variable, without default. Helps running custom deployments.
Low.

[config] add support for third party s3 which uses path-style buckets

---

test/acceptance/js/FilestoreApp.js
test/acceptance/js/FilestoreTests.js
test/unit/js/ImageOptimiserTests.js
test/unit/js/KeybuilderTests.js
test/unit/js/S3PersistorTests.js
test/unit/js/SafeExecTests.js

These are all rather unrelated patches -- they all touch tests. So I recommend reviewing them on a per-commit basis. 
- [misc] test/unit: add missing require stubs for metrics and settings f0c8eac
less verbose tests and slightly better performance due to omitted imports
- [misc] test/unit: add missing globals that are lazy loaded 2300727
preparation for node 12
- [misc] test/unit: KeybuilderTests: use a unique suite label 3b7e33a
fix copy and paste error. useful for limiting the number of running test suites via `MOCHA_GREP`
- [misc] test/acceptance: harden the startup check for s3 57edd4b
minio -- my s3 replacement -- returns a 403 without auth, failing the current startup check. Placing a file in s3 as the startup check functions as an extended healthcheck too. Also limits the timeout …

[misc] test cleanup

---

package-lock.json
package.json

The latest version of metrics doesn't overwrite `UV_THREADPOOL_SIZE` if you explicitly set it.
This allows us to override `UV_THREADPOOL_SIZE` to see if it helps with lockups under load.

Bump metrics to 2.5.0

---

app.js
app/js/Errors.js
app/js/FSPersistor.js
app/js/FileController.js
app/js/FileHandler.js
app/js/GcsPersistor.js
app/js/KeyBuilder.js
app/js/PersistorHelper.js
app/js/PersistorManager.js
app/js/S3Persistor.js
config/settings.defaults.coffee
docker-compose.ci.yml
docker-compose.yml
package-lock.json
package.json
test/acceptance/deps/Dockerfile.fake-gcs
test/acceptance/deps/Dockerfile.s3mock
test/acceptance/deps/healthcheck.sh
test/acceptance/js/FilestoreTests.js
test/acceptance/js/TestConfig.js
test/acceptance/js/TestHelper.js
test/unit/js/FSPersistorTests.js
test/unit/js/FileControllerTests.js
test/unit/js/FileHandlerTests.js
test/unit/js/GcsPersistorTests.js
test/unit/js/S3PersistorTests.js

Add a persistor to talk to GCS instead of S3.
~Targeted onto #78~ (#78 was merged)
Finishes off the work for overleaf/google-ops#731
It's a big chunk of new code I'm afraid. It's very similar to the S3 stuff obviously, but using the official GCS client.
This has only been tested as far as unit/acceptance tests go. Next steps should be to:
- Get this working with the dev env, using `fake-gcs-server` and migrating from FS
- Test on staging
I imagine both of these will show problems, but as the GCS stuff has only been tested against the fake server, "test on staging" is likely to be the more difficult.
We'll need to change the settings to use GCS and fall back to S3, once we're ready and have the necessary buckets and permissions in place.
The service account for the pods running this should …

Add GCS Persistor

---

app/js/MigrationPersistor.js
test/acceptance/js/FilestoreTests.js

Falling back to S3 custom buckets (e.g. for latexqc) was not working, as the fallback bucket would be null if not defined in the settings.
We should pass through the bucket instead of returning nothing, if we don't have a fallback for it. The worst that could happen is a 4xx error.
I've tested this on staging. Properly this time.
I made the change to the tests first, and they failed until I added the fix to `MigrationPersistor.js`

Fix fallback to custom s3 buckets

---

app/js/GcsPersistor.js
app/js/PersistorHelper.js
app/js/S3Persistor.js
package-lock.json
package.json
test/unit/js/FSPersistorTests.js
test/unit/js/GcsPersistorTests.js
test/unit/js/S3PersistorTests.js

Adds a new `Stream.Transform` class that calculates the hash *and* byte count of a stream and passes it through. This removes the need for a separate metered stream module.
The idea here is that we have one single pipeline, instead if splitting the incoming data into two.
I've left in the `calculateStreamMd5` method, as this is called from the MD5-calculation endpoint and is useful when we want an MD5 but don't want to pass the stream through to anything else.
The dependency on `stream-meter` has been removed.
I've removed a couple of unit tests about egress/ingress metrics, as these were faffy to implement. I think there is very good acceptance-test coverage here, so I don't think that this is a problem.
Most things.

Use single pipeline when calculating md5

---

app/js/GcsPersistor.js
app/js/PersistorHelper.js
app/js/S3Persistor.js
test/acceptance/js/FilestoreTests.js
test/unit/js/GcsPersistorTests.js
test/unit/js/S3PersistorTests.js

Try to fix handle leaks.
The most significant thing here was adding https://github.com/overleaf/filestore/commit/04c41816fe690155f325d9024ee11516533b4326 - which fails acceptance tests on unhandled promise rejection. This pointed out unhandled errors from the `pipeline` method when waiting for streams to become readable, which are fixed in https://github.com/overleaf/filestore/commit/d6170c95ee6e2520ad834b133d48cf45a022d9ae
For belt and braces, we also use autodestroy on the transform stream: https://github.com/overleaf/filestore/commit/cab1e3c21e0bc1129f52fdafc58914cf3b352cd1
And pass errors to the `destroy` method in the error handler: https://github.com/overleaf/filestore/commit/f4d08b73c195042cf93f7ac791c3a0932646c1ae
I don't know if either of these will make a difference, but they …

(Hopefully) fix handle leaks

---

app/js/FileController.js
app/js/PersistorHelper.js

It looks like we are not doing anything on an `ERR_STREAM_PREMATURE_CLOSE` error. I think this was an attempt to not write errors to the logs when this happens.
On other errors, we are passing on to `next`. On no error, I would assume that the request has completed successfully. This patch tries to close the connection when a premature-close error occurs, rather than leaving it hanging.
See further diagnosis at: https://github.com/overleaf/issues/issues/2880#issuecomment-606033804

Call end() when handing ERR_STREAM_PREMATURE_CLOSE

---

app/js/FileHandler.js
test/unit/js/FileHandlerTests.js

Don't call `deleteDirectory` on the `converted-cache` folder when inserting or deleting files, unless conversions are enabled.
Slack discussion: https://digital-science.slack.com/archives/G6256GXGS/p1585663651303300
It's highly probable that we don't need to delete the directory on `insertFile` based on how we expect uploads to work, but I would rather change as little as possible so I'm leaving this in place for now.

Only delete the converted-cache folder if conversions are enabled

---

app/js/PersistorHelper.js

This modifies the `getReadyPipeline` helper to do two things:
* Ensures that streams are destroyed on error, when the error is caught before the promise rejects
* Calls `destroy` on streams in the pipeline when the next one emits `close`
I realise that this is throwing stuff at the wall to see what sticks somewhat, but here we are.

Destroy download streams on close

---

app/js/FileController.js
app/js/PersistorHelper.js
test/acceptance/js/FilestoreTests.js
test/unit/js/GcsPersistorTests.js
test/unit/js/S3PersistorTests.js

Adds an acceptance test to look for socket leaks, and then modifies the pipeline mechanism to ensure that it passes.
The modifications to the mechanism avoid the use of `pipeline` which can cause problems in this particular situation.
Fixes overleaf/issues#2880 (I hope!)
Took some time this one because `pipeline` is supposed to do this.
Some points worth noting:
* The acceptance test fails in the same way as it does on production, in that the leaked sockets look the same (recv queue but no send queue)
* The acceptance test fails for S3 and GCS in the same way, which is potentially a source of earlier confusion
* Passing back the stream returned from `GCS.bucket.file.createReadStream` directly to `FileController` *does not* fix the problem
I spent some time watching events on a debugger. …

Ensure streams are drained when a pipeline fails

---

app/js/RequestLogger.js

The error handler mistakenly sent two responses on error, the first
being a 200.
https://github.com/overleaf/issues/issues/2925
Everything related to file storage.

Fix error handler returning two responses

---

package-lock.json
package.json

Google recommend installing `fast-crc32c` to improve the performance of crc computation:
https://googleapis.dev/nodejs/storage/latest/File.html#createWriteStream
It's possible that this will help reduce resource usage if we add it.

Add fast-crc32c library

---

app/js/FSPersistor.js
app/js/FileController.js
app/js/FileHandler.js
app/js/GcsPersistor.js
app/js/MigrationPersistor.js
app/js/S3Persistor.js
config/settings.defaults.coffee
test/unit/js/FileControllerTests.js
test/unit/js/FileHandlerTests.js
test/unit/js/GcsPersistorTests.js

Add a mechanism to retrieve a signed URL from filestore and redirect to it, instead of proxying the file directly.
Falls back to proxying if the url can't be retrieved.
Fixes overleaf/issues#2937
I've only added support for redirects to the GCS persistor, as this is where the bulk of the traffic goes. If we're using the S3 persistor now it's because we're falling back to an unusual bucket.
It's running in staging with redirect URLs only enabled for `filestore-readonly`. I think this is sensible for now as that's where the bulk of the load comes from. Compiles still work and I'm seeing hits on the `file_redirect` metric.
I couldn't get acceptance tests working against this, or signed URLs working in dev. Tested in staging.
Requires a settings change to proxy the files - assuming we're just …

Add support for redirecting to signed URLs

---

app/js/FileHandler.js
test/unit/js/FileHandlerTests.js

Updates regular expression matcher for file keys to support templates API.
Shouldn't have any, the regular expression is backwards compatible.

Fixed regular expression to insert/delete files not supporting templates API

---

app/js/GcsPersistor.js
test/acceptance/deps/Dockerfile.fake-gcs
test/unit/js/GcsPersistorTests.js

A recent change to `fake-gcs-server` broke the filestore tests, which I initially assumed to be a bug in a newer version of the fake server. It turns out however that I'd actually matched my GCS implementation to the old, buggy behaviour.
See fsouza/fake-gcs-server#263
I've pinned `fake-gcs-server` back to `latest` rather than a specific version. Given that we caught this bug via a fake-gcs update/bugfix I think it better to leave it like this.
Downloading files from GCS with a range header.

Fix Filestore returning one-too-many bytes when given a range

---

config/settings.defaults.coffee
test/unit/js/SettingsTests.js

The new Object Persistor module expects to see a couple of config settings in different places. This puts them in the right place.
Implemented in overleaf/object-persistor#1 and #122

Move config settings to correct place for new persistor module

---

app.js

The Google trace agent wants to be loaded before other things, and it's `logger-sharelatex` that sets this up - so needs to be loaded first.

Load logger module first

---

app.js

If pressent, use `METRICS_APP_NAME` env var to initialise logging and metrics, instead of the default `filestore`.
This allows us to generate profiling data from filestore-readonly and filestore separately, which is useful in some cases as the apps are used quite differently.
This also initialises the logging module before requiring the metrics module, in case this helps with the error where initialising the trace agent complains because some modules have already been loaded. I haven't tested if this solves that problem, but I don't think it can hurt.
This only does something if `METRICS_APP_NAME` is set, which needs to be set explicitly in the jinja file. Will need a separate google-ops PR for that.
Should be deployed alongside https://github.com/overleaf/google-ops/pull/1162
May affect …

Use METRICS_APP_NAME env var to initialise metrics, if present

---

package-lock.json
package.json

`@google-cloud/storage` is no longer directly used by Filestore, and is instead pulled in by `object-persistor` which is pulling in a different version.
It's still used by the acceptance tests, so I've upgraded this and made it a dev dependency instead.
It's already been tested with a canary deploy.
No hash downgrades in package-lock! :tada:

Move @google-cloud/storage to a dev dependency

---

package-lock.json

Deleting an empty directory can cause problems in the dev environment. There is a fix here:
https://github.com/overleaf/object-persistor/pull/12
This patch pulls in that change.
Fix: https://github.com/overleaf/object-persistor/pull/12
Should unblock: https://github.com/overleaf/web-internal/pull/3269
Just a package-lock upgrade. I've checked the commit hash against the head of master in object-persistor.
Should be fairly limited.

Upgrade object-persistor to latest version

---

app.js
app/js/FileController.js
app/js/FileConverter.js
app/js/ImageOptimiser.js
app/js/LocalFileWriter.js
app/js/PersistorManager.js
app/js/RequestLogger.js
package-lock.json
package.json
test/unit/js/FileControllerTests.js
test/unit/js/FileConverterTests.js
test/unit/js/ImageOptimiserTests.js
test/unit/js/LocalFileWriterTests.js

For https://github.com/overleaf/issues/issues/3502
- renamed package from `metrics-sharelatex` to `@overleaf/metrics`
- drop support for statsd backend
- decaffeinate
- compress `/metrics` response using gzip
- bump debugging agents to latest versions
- expose prometheus interfaces for custom metrics (custom tags)
- cleanup of open sockets metrics
- fix deprecation warnings for header access
For https://github.com/overleaf/issues/issues/3502
High. Incomplete metrics collection.
- create a new project
- open a project in the editor
- make changes to a document, reload the editor to check persistence
- compile a project
- open the history tab in the editor
- all services seem to be running fine in the dev-env
- check for compression on the `/metrics` endpoint:
- `$ curl …

[misc] bump metrics module to 3.4.1

---

package-lock.json
package.json

For https://github.com/overleaf/issues/issues/3731
Installing npm packages via git is flaky (https://github.com/overleaf/third-party-references/pull/42).
This PR is switching the installation of the @overleaf/object-persistor package to a tar-ball install.
For https://github.com/overleaf/issues/issues/3731
Low. The tests are not working without this package being properly installed, so the chance of it breaking in prod are low.

[misc] install @overleaf/object-persistor from tar-ball

---

docker-compose.ci.yml
docker-compose.yml

Implementation of https://github.com/overleaf/docstore/pull/83/files for filestore.
See: https://github.com/overleaf/issues/issues/3890
Only affects ci.

pin fake-gcs to 1.21.2 to prevent acceptance-test errors

---

.eslintrc
Makefile
buildscript.txt

For https://github.com/overleaf/issues/issues/3851
Uses https://github.com/overleaf/dev-environment/pull/470
> This PR is adding linting rules for flagging imports from npm that are not properly specified in the package.json. Either they are missing at all and the `node_modules/` entry is there by chance via another dependency, or they are specified in the wrong section, e.g. using a `devDependency` in `app/js/`.
For https://github.com/overleaf/issues/issues/3851
Uses https://github.com/overleaf/dev-environment/pull/470
Low.

[misc] add linting for missing explicit dependencies and fix any errors
